# Generated by Django 3.1 on 2021-06-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('assignment_start_time', models.TimeField(blank=True, null=True)),
                ('assignment_end_time', models.TimeField(blank=True, null=True)),
                ('assignment_detail', models.CharField(default='', max_length=255)),
                ('assignment_fileUpload', models.FileField(upload_to='uploads/')),
                ('dept', models.CharField(default='', max_length=255)),
                ('assignment_marksOutOf', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.teacher', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(default='', max_length=255)),
                ('exam_type', models.CharField(default='', max_length=255)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_start_time', models.TimeField(blank=True, null=True)),
                ('exam_end_time', models.TimeField(blank=True, null=True)),
                ('exam_detail', models.CharField(default='', max_length=255)),
                ('exam_fileUpload', models.FileField(upload_to='uploads/')),
                ('dept', models.CharField(default='', max_length=255)),
                ('exam_marksOutOf', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.teacher', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(default='', max_length=255)),
                ('query_subject', models.CharField(default='', max_length=255)),
                ('msg', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('stud_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('submittedfile', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('emarksObtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('emarksOutOf', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('submittedfile', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amarksObtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amarksOutOf', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.assignment')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username')),
            ],
        ),
    ]
