# Generated by Django 3.1 on 2021-06-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocp_app', '0002_auto_20210530_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_id', models.CharField(default='', max_length=50)),
                ('dept', models.CharField(default='', max_length=255)),
                ('exam_type', models.CharField(default='', max_length=255)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_id', models.CharField(default='', max_length=50)),
                ('exam_type', models.CharField(default='', max_length=255)),
                ('query_subject', models.CharField(default='', max_length=255)),
                ('msg', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(default='', max_length=255)),
                ('exam_type', models.CharField(default='', max_length=15)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_start_time', models.TimeField(blank=True, null=True)),
                ('exam_end_time', models.TimeField(blank=True, null=True)),
                ('exam_detail', models.CharField(default='', max_length=255)),
                ('exam_fileUpload', models.FileField(upload_to='uploads/')),
                ('dept', models.CharField(default='', max_length=255)),
                ('uploaded_by', models.CharField(default='', max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('assignment_start_time', models.TimeField(blank=True, null=True)),
                ('assignment_end_time', models.TimeField(blank=True, null=True)),
                ('assignment_detail', models.CharField(default='', max_length=255)),
                ('assignment_fileUpload', models.FileField(upload_to='uploads/')),
                ('dept', models.CharField(default='', max_length=255)),
                ('uploaded_by', models.CharField(default='', max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_id', models.CharField(default='', max_length=50)),
                ('submittedfile', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
            ],
        ),
    ]
