# Generated by Django 3.1 on 2021-06-03 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0003_auto_20210603_2351'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='stud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.teacher', to_field='username'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.teacher', to_field='username'),
        ),
        migrations.AlterField(
            model_name='query',
            name='stud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username'),
        ),
        migrations.AlterField(
            model_name='result',
            name='stud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username'),
        ),
    ]
