# Generated by Django 3.1 on 2021-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_marksOutOf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_marksOutOf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
