# Generated by Django 3.1 on 2021-06-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210603_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
