# Generated by Django 3.1 on 2021-06-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0006_auto_20210610_2008'),
        ('exam', '0003_auto_20210608_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AssignmentAnswer',
        ),
        migrations.RenameField(
            model_name='assignmentanswer',
            old_name='ans_id',
            new_name='assign_ans_id',
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('exam_ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('submittedfile', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.courses')),
                ('stud_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.student', to_field='username')),
            ],
        ),
    ]
