# Generated by Django 3.1 on 2021-06-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210620_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentanswer',
            old_name='stud_id',
            new_name='studid',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='stud_id',
            new_name='studid',
        ),
    ]
