# Generated by Django 3.1 on 2021-06-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210620_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentanswer',
            old_name='studid',
            new_name='stud',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='studid',
            new_name='stud',
        ),
    ]
