# Generated by Django 3.1 on 2021-06-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210620_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentanswer',
            old_name='assign_ans_id',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='exam_ans_id',
            new_name='sno',
        ),
        migrations.AddField(
            model_name='assignmentanswer',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.assignment'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
