# Generated by Django 3.1.4 on 2021-01-03 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpStud',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=15)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
