# Generated by Django 3.0.3 on 2021-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('dept_id', models.CharField(default='', max_length=3, unique=True)),
                ('dept_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpStud',
        ),
    ]
