# Generated by Django 3.1 on 2021-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('dept_id', models.CharField(default='', max_length=3)),
                ('dept_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
