# Generated by Django 3.0.3 on 2021-05-30 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=150)),
                ('announcement_file', models.FileField(upload_to='announcements/')),
                ('file_type', models.CharField(max_length=3)),
                ('date_of_announcement', models.DateField(auto_now=True)),
                ('time_of_announcement', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(default=' ', max_length=150, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default=' ', max_length=255)),
                ('year', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('dept_id', models.CharField(default='', max_length=3, unique=True)),
                ('dept_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=255)),
                ('msg', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='', upload_to='')),
                ('username', models.CharField(default='', max_length=15)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password', models.CharField(default='', max_length=20)),
                ('year', models.CharField(default='0', max_length=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField()),
                ('material_type', models.CharField(max_length=15)),
                ('material_DESC', models.CharField(max_length=15)),
                ('material', models.FileField(upload_to='uploads/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tnum', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default=' ', upload_to='')),
                ('username', models.CharField(default='', max_length=15)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('designation', models.CharField(default=' ', max_length=15)),
                ('password', models.CharField(default='', max_length=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses')),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpStud',
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id'),
        ),
    ]
