# Generated by Django 3.0.3 on 2021-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='r_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
