# Generated by Django 3.0.3 on 2021-04-02 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(default=' ', max_length=150, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='', upload_to='')),
                ('username', models.CharField(default='', max_length=15)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpStud',
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id'),
        ),
    ]
