# Generated by Django 3.1 on 2021-06-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0002_auto_20210530_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
