# Generated by Django 3.0.3 on 2021-04-02 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0003_auto_20210402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tnum', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default=' ', upload_to='')),
                ('username', models.CharField(default='', max_length=15)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('designation', models.CharField(default=' ', max_length=15)),
                ('password', models.CharField(default='', max_length=20)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField()),
                ('material_type', models.CharField(max_length=15)),
                ('material_DESC', models.CharField(max_length=15)),
                ('material', models.FileField(upload_to='uploads/')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Courses')),
                ('departmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=150)),
                ('announcement_file', models.FileField(upload_to='announcements/')),
                ('date_of_announcement', models.DateField(blank=True, null=True)),
                ('time_of_announcement', models.TimeField()),
                ('departmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id')),
            ],
        ),
    ]
