# Generated by Django 3.1 on 2021-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0003_announcement_courses_student_studymaterial_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=255)),
                ('msg', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
