# Generated by Django 3.0.3 on 2021-06-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0003_auto_20210628_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
