# Generated by Django 3.1 on 2021-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0003_auto_20210603_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
    ]
