# Generated by Django 3.1 on 2021-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0004_auto_20210402_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
