# Generated by Django 3.0.3 on 2021-06-10 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0004_auto_20210603_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='date_of_announcement',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='time_of_announcement',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
