# Generated by Django 3.0.3 on 2021-05-30 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0005_forum_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_of_announcement',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.TimeField(auto_now=True),
        ),
    ]
