# Generated by Django 3.1 on 2021-04-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0005_auto_20210402_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='dept_id',
            new_name='dept',
        ),
    ]
