# Generated by Django 3.0.3 on 2021-06-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0005_auto_20210610_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='date_of_announcement',
            new_name='date_of_upload',
        ),
        migrations.RenameField(
            model_name='studymaterial',
            old_name='time_of_announcement',
            new_name='time_of_upload',
        ),
    ]
