# Generated by Django 3.0.3 on 2021-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0006_auto_20210530_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_of_announcement',
            field=models.DateField(auto_now=True),
        ),
    ]
