# Generated by Django 3.1 on 2021-04-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0006_auto_20210402_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='departmet',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studymaterial',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studymaterial',
            old_name='departmet',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='courses',
            new_name='course',
        ),
    ]
