# Generated by Django 3.1 on 2021-04-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0007_auto_20210402_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
