# Generated by Django 3.0.3 on 2021-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0009_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
