# Generated by Django 3.0.3 on 2021-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0010_auto_20210503_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='year',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
