# Generated by Django 3.0.3 on 2021-05-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0011_auto_20210503_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocp_app.Department', to_field='dept_id'),
        ),
    ]
