# Generated by Django 3.0.3 on 2021-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_app', '0012_auto_20210505_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file_type',
            field=models.CharField(default='img', max_length=3),
            preserve_default=False,
        ),
    ]
